name: Initialise the project from template

on:
  create: 
    branches:
      - master
      - main

jobs:
  rename-project:
    runs-on: ubuntu-latest
    if: ${{ github.repository != 'kierenfunk/python-template' }}
    steps:
      - uses: actions/checkout@v3
        with:
          # by default, it uses a depth of 1
          # this fetches all history so that we can read each commit
          fetch-depth: 0
          ref: ${{ github.head_ref }}
          
      - run: echo "REPOSITORY_NAME=$(echo '${{ github.repository }}' | awk -F '/' '{print $2}' | tr '-' '_' | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV
      - run: echo "REPOSITORY_URLNAME=$(echo '${{ github.repository }}' | awk -F '/' '{print $2}')" >> $GITHUB_ENV
      - run: ./init.sh "${{ env.REPOSITORY_NAME }}" "${{ env.REPOSITORY_URLNAME }}"
      - run: rm init.sh .github/workflows/init.yml

      - name: Get last commit message
        id: last-commit-message
        run: |
          echo "::set-output name=msg::$(git log -1 --pretty=%s)"
      
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "✅ Ready to clone and code."
          # commit_message: ${{ steps.last-commit-message.outputs.msg }}
          # commit_options: '--amend --no-edit'
          push_options: --force